# Usar la imagen oficial de Nginx
FROM nginx:alpine

# Copiar los archivos de tu proyecto frontend al directorio predeterminado de Nginx
COPY ./ /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80
