FROM python:3.13-slim

# Copiar solo el archivo 'requirements.txt' primero y luego instalar las dependencias
COPY app/requirements.txt /app/

RUN pip install --no-cache-dir -r /app/requirements.txt

# Copiar el resto de la carpeta 'app' al contenedor
COPY app /app

# Exponer el puerto en el que la app se ejecutará
EXPOSE 5000

# Ejecutar flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
